name: tiktaktoo_pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  static-code-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Amazon Corretto 22
        uses: actions/setup-java@v2
        with:
          distribution: 'corretto'
          java-version: '22'

      - name: Run static code analysis
        run: ./gradlew checkstyleMain checkstyleTest

      - name: Verify code formatting
        run: ./gradlew spotlessCheck

  unit-tests:
    runs-on: ubuntu-latest
    needs: static-code-analysis
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Amazon Corretto 22
        uses: actions/setup-java@v2
        with:
          distribution: 'corretto'
          java-version: '22'

      - name: Run unit tests
        run: ./gradlew test

  build:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Amazon Corretto 22
        uses: actions/setup-java@v2
        with:
          distribution: 'corretto'
          java-version: '22'

      - name: Build Java application
        run: ./gradlew build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: user/repository:latest
